import {
  Box,
  Container,
  Heading,
  HStack,
  Text,
  VStack,
  Badge,
  Icon,
} from "@chakra-ui/react";
import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { FaArrowRight } from "react-icons/fa";

// MAIN APP STATE
import { useMainApp } from "../AppState/Context";

const history = () => {
  // INITIALIZATIONS
  // main app state
  const mainState = useMainApp();
  const router = useRouter();

  return (
    <div style={{ width: "calc(100% - 30rem)", marginLeft: "5rem" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Container p={"2rem"} m="0" minW={"full"} bg="gray.100" minH={"100vh"}>
          <Box>
            <Heading mb="2rem">Shopping History</Heading>
            <VStack justify={"flex-start"}>
              {mainState.mainappstate.history?.map((item, index) => {
                return (
                  <HStack
                    key={index}
                    minW={"full"}
                    justify={"space-between"}
                    shadow={"2xl"}
                    bg="white"
                    p="1rem"
                  >
                    <Box>{item.name}</Box>
                    <Box
                      display={"inline-flex"}
                      gap="1rem"
                      alignItems={"center"}
                    >
                      <Text color={"gray"}>{item.date}</Text>
                      <Badge
                        p="1rem"
                        borderRadius={"1rem"}
                        variant={"outline"}
                        colorScheme={
                          item.status == "incomplete" ? "red" : "blue"
                        }
                      >
                        {item.status}
                      </Badge>
                      <Icon
                        as={FaArrowRight}
                        onClick={() => {
                          router.push(`/history/${item.name}`);
                        }}
                      />
                    </Box>
                  </HStack>
                );
              })}
              {mainState.mainappstate.history.length < 1 && (
                <Text>No lists found</Text>
              )}
            </VStack>
          </Box>
        </Container>
      </div>
    </div>
  );
};

export default history;
