import {Container} from "@chakra-ui/react";
import Head from "next/head";

export default function Items({mainState}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container maxW={"100%"}>adwwd</Container>
    </div>
  );
}
