import {
  Box,
  Container,
  Heading,
  Text,
  VStack,
  Card,
  CardBody,
} from "@chakra-ui/react";
import Head from "next/head";
import {CustomCardUI} from "../components/CustomCard/CustomCardCmp";

export default function Items({mainState}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container maxW={"100%"}>
        <Text as={"b"} fontSize="4xl">
          Welcome to schoolx
        </Text>
        <VStack align={"start"}>
          <Heading>Upcoming Events</Heading>
          {/* <CustomCardUI /> */}
          <Card>
            <CardBody>
              <Text>
                View a summary of all your customers over the last month.
              </Text>
            </CardBody>
          </Card>
          <Heading>Announcements</Heading>
        </VStack>
      </Container>
    </div>
  );
}
