import {
  Box,
  Container,
  Heading,
  HStack,
  Text,
  VStack,
  Input,
  InputLeftElement,
  InputGroup,
  Icon,
} from "@chakra-ui/react";
import Head from "next/head";

import {FaSearch} from "react-icons/fa";

import ItemCard from "../components/ItemCard/ItemCard";

export default function Items({mainState}) {
  return (
    <div style={{marginLeft: "5rem"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div>
        <Container p={"2rem"} m="0" minW={"full"} bg="gray.100" minH={"100vh"}>
          hello
        </Container>
      </div>
    </div>
  );
}
