import React from "react";
import {
  Box,
  Button,
  Container,
  Heading,
  HStack,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

// MAIN APP STATE
import { useMainApp } from "../../AppState/Context";

const SavedList = () => {
  // INITIALIZATIONS
  // router
  // url query name
  // main app state
  // current saved list
  const router = useRouter();
  const { ListName } = router.query;
  const mainState = useMainApp();
  const savedList = mainState.mainappstate.history.find((item) => {
    return item.name == ListName;
  });

  console.log(savedList);

  return (
    <div style={{ width: "calc(100% - 30rem)", marginLeft: "5rem" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Container p={"2rem"} m="0" minW={"full"} bg="gray.100" minH={"100vh"}>
          <Box mb="3rem">
            <Heading mb={"1rem"} color={"orange.600"} fontWeight="extrabold">
              {ListName}
            </Heading>
            {savedList?.date !== undefined && (
              <Text color={"gray"}>{savedList.date}</Text>
            )}
          </Box>

          {/* shopping list */}
          {savedList !== undefined && (
            <VStack align={"flex-start"}>
              {Object.keys(savedList.list).map((outerItem, index) => {
                const temp = savedList.list[outerItem].map((innerItem, i) => {
                  return (
                    <Box
                      display={"inline-flex"}
                      p="1rem"
                      shadow={"base"}
                      w="15rem"
                      justifyContent={"space-between"}
                      bg="white"
                    >
                      <Text color={"black"}>{innerItem.name}</Text>
                      <Text color={"black"}>{innerItem.quantity}</Text>
                    </Box>
                  );
                });

                return (
                  <Box key={index} mb="2rem">
                    <Text color="gray" mb="1rem">
                      {outerItem}
                    </Text>
                    <HStack spacing={"1rem"}>{temp}</HStack>
                  </Box>
                );
              })}
              <Button>Set as Active List</Button>
            </VStack>
          )}
        </Container>
      </div>
    </div>
  );
};

export default SavedList;
